version: "3.5"
services:
  # frontend:
  #   build: ./frontend
  #   command: python app.py
  #   ports:
  #     - target: 3000
  #       published: 3000
  #   networks:
  #     - counter-net
  backend:
    build: ./backend
    ports:
      - 8000:8000
    depends_on:
      - mongodb
    networks:
      counter-net:
    links:
      - mongodb
    secrets:
      - backend_env
  mongodb:
    build: ./mongodb
    ports:
      - 27017:27017
    networks:
      counter-net:
    environment:
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongodb_root_password
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongodb_root_username
      MONGO_INITDB_DATABASE: admin
      MONGO_USERNAME: /run/secrets/mongodb_username
      MONGO_PASSWORD: /run/secrets/mongodb_password
      MONGO_DATABASE: parrot
    secrets:
      - mongodb_root_password
      - mongodb_root_username
      - mongodb_password
      - mongodb_username

networks:
  counter-net:

secrets:
  backend_env:
    file: ./.backend_env
  mongodb_root_password:
    file: ./.mongodb_root_password
  mongodb_root_username:
    file: ./.mongodb_root_username
  mongodb_password:
    file: ./.mongodb_password
  mongodb_username:
    file: ./.mongodb_username
