version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
        name: Backend: install packages
        command: cd backend && npm install
      - run:
        name: Backend: run test
        command: cd backend && npm test
