// navs
export const SET_TOP_NAV_PROPS = 'SET_TOP_NAV_PROPS';
export const SET_TOP_NAV_TYPE = 'SET_TOP_NAV_TYPE';
export const SET_SIDENAV_ISOPEN = 'SET_SIDENAV_ISOPEN';

// domains
export const ADD_TO_DOMAIN_LIST = 'DOMAINS/ADD_TO_DOMAIN_LIST';
export const UPDATE_DOMAIN_LIST = 'DOMAINS/UPDATE_DOMAIN_LIST';
export const SET_DOMAIN_LIST_AGENT = 'DOMAINS/SET_DOMAIN_LIST_AGENT';
export const CREATE_DOMAIN = 'DOMAINS/CREATE_DOMAIN';
export const SET_CURRENT_DOMAIN = 'DOMAINS/SET_CURRENT_DOMAIN';
export const UPDATE_CURRENT_DOMAIN = 'DOMAINS/UPDATE_CURRENT_DOMAIN';

// agents
export const CREATE_AGENT = 'AGENTS/CREATE_AGENT';
export const GET_ALL_AGENTS = 'AGENTS/GET_ALL_AGENTS';
export const UPDATE_AGENT_LIST = 'AGENTS/UPDATE_AGENT_LIST';
export const SET_CURRENT_AGENT = 'AGENTS/SET_CURRENT_AGENT';
export const UPDATE_CURRENT_AGENT = 'AGENTS/UPDATE_CURRENT_AGENT';
export const CREATE_AGENT_FAILED = 'AGENTS/CREATE_AGENT_FAILED';
export const CREATE_AGENT_SUCCEEDED = 'AGENTS/CREATE_AGENT_SUCCEEDED';

// actions
export const CREATE_ACTION = 'ACTIONS/CREATE_ACTION';
export const CREATE_ACTION_FAILED = 'ACTIONS/CREATE_ACTION_FAILED';
export const CREATE_ACTION_SUCCEEDED = 'ACTIONS/CREATE_ACTION_SUCCEEDED';
export const SET_CURRENT_ACTION = 'ACTIONS/SET_CURRENT_ACTION';
export const GET_ALL_ACTIONS = 'ACTIONS/GET_ALL_ACTIONS';
export const UPDATE_ACTION_LIST = 'ACTIONS/UPDATE_ACTION_LIST';
export const UPDATE_CURRENT_ACTION = 'ACTIONS/UPDATE_CURRENT_ACTION';
export const UPDATE_ACTION = 'ACTIONS/UPDATE_ACTION';
export const DELETE_ACTION = 'ACTIONS/DELETE_ACTION';
export const DELETE_ACTION_FROM_LIST = 'ACTIONS/DELETE_ACTION_FROM_LIST';

// intents
export const CREATE_INTENT = 'INTENTS/CREATE_INTENT';
export const UPDATE_INTENT_LIST = 'INTENTS/UPDATE_INTENT_LIST';
export const SET_INTENT_LIST_DOMAIN = 'INTENTS/SET_INTENT_LIST_DOMAIN';
export const ADD_TO_INTENT_LIST = 'INTENTS/ADD_TO_INTENT_LIST';
export const SET_CURRENT_INTENT = 'INTENTS/SET_CURRENT_INTENT';
export const DELETE_INTENT = 'INTENTS/DELETE_INTENT';
export const DELETE_INTENT_FROM_LIST = 'INTENTS/DELETE_INTENT_FROM_LIST';
export const UPDATE_CURRENT_INTENT = 'INTENTS/UPDATE_CURRENT_INTENT';
export const UPDATE_INTENT = 'INTENTS/UPDATE_INTENT';

// stories
export const SET_STORY_LIST_DOMAIN = 'STORIES/SET_STORY_LIST_DOMAIN';
export const UPDATE_STORY_LIST = 'STORIES/UPDATE_STORY_LIST';
export const CREATE_STORY = 'STORIES/CREATE_STORY';
export const ADD_TO_STORY_LIST = 'STORIES/ADD_TO_STORY_LIST';
export const SET_CURRENT_STORY_ID = 'STORIES/SET_CURRENT_STORY_ID';
export const UPDATE_CURRENT_STORY = 'STORIES/UPDATE_CURRENT_STORY';
export const MODIFY_STORY = 'STORIES/MODIFY_STORY';
export const ADD_ACTION_TO_STORY = 'STORIES/ADD_ACTION_TO_STORY';
export const ADD_INTENT_TO_STORY = 'STORIES/ADD_INTENT_TO_STORY';
export const UPDATE_STORY_IN_STORY_LIST = 'STORIES/UPDATE_STORY_IN_STORY_LIST';
