// navs
export const SET_TOP_NAV_PROPS = 'SET_TOP_NAV_PROPS';
export const SET_TOP_NAV_TYPE = 'SET_TOP_NAV_TYPE';
export const SET_SIDENAV_ISOPEN = 'SET_SIDENAV_ISOPEN';

// domains
export const ADD_TO_DOMAIN_LIST = 'DOMAINS/ADD_TO_DOMAIN_LIST';
export const UPDATE_DOMAIN_LIST = 'DOMAINS/UPDATE_DOMAIN_LIST';
export const SET_DOMAIN_LIST_AGENT = 'DOMAINS/SET_DOMAIN_LIST_AGENT';
export const CREATE_DOMAIN = 'DOMAINS/CREATE_DOMAIN';

// agents
export const CREATE_AGENT = 'AGENTS/CREATE_AGENT';
export const GET_ALL_AGENTS = 'AGENTS/GET_ALL_AGENTS';
export const UPDATE_AGENT_LIST = 'AGENTS/UPDATE_AGENTS_LIST';
// export const ADD_TO_AGENT_LIST = 'AGENTS/ADD_TO_AGENTS_LIST';
export const SET_CURRENT_AGENT = 'AGENTS/SET_CURRENT_AGENT';
export const UPDATE_CURRENT_AGENT = 'AGENTS/UPDATE_CURRENT_AGENT';
export const CREATE_AGENT_FAILED = 'CREATE_AGENT_FAILED';
export const CREATE_AGENT_SUCCEEDED = 'CREATE_AGENT_SUCCEEDED';
